# Dockerfile.backend
FROM python:3.11-slim

WORKDIR /app
COPY .env ./
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ ./backend/
COPY kpi_project/ ./kpi_project/

WORKDIR /app/backend
CMD ["gunicorn", "kpi_project.wsgi:application", "--bind", "0.0.0.0:8000"]
