name: Deploy to Test Server

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USER }}
          key: ${{ secrets.TEST_SERVER_SSH_KEY }}
          script: |
            cd C:\KPI_PROJECT
            git pull origin develop
            docker compose pull
            docker compose up -d --build


      - name: Run Smoke Tests
        shell: cmd
        run: |
          cd C:\KPI_PROJECT\scripts
          smoke.bat

